SET SCHEMA PRGOEL; 

DROP TYPE PAL_SVM_TRAINING_T;
CREATE TYPE PAL_SVM_TRAINING_T AS TABLE ( 
	ID INTEGER, 
	ATTRIBUTE1 DOUBLE, 
	ATTRIBUTE2 DOUBLE, 
	ATTRIBUTE3 DOUBLE,
	ATTRIBUTE4 VARCHAR(10),
	LABEL INTEGER
);

DROP TYPE PAL_CONTROL_T;
CREATE TYPE PAL_CONTROL_T AS TABLE( 
	NAME VARCHAR(50), 
	INTARGS INTEGER, 
	DOUBLEARGS DOUBLE, 
	STRINGARGS VARCHAR(100)
);

DROP TYPE PAL_SVM_MODEL_T;
CREATE TYPE PAL_SVM_MODEL_T AS TABLE( ID VARCHAR(50), MODEL VARCHAR(5000));

DROP TABLE PAL_SVM_PDATA_TBL;
CREATE TABLE PAL_SVM_PDATA_TBL("POSITION" INT, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO PAL_SVM_PDATA_TBL VALUES (1,'PRGOEL','PAL_SVM_TRAINING_T','IN');
INSERT INTO PAL_SVM_PDATA_TBL VALUES (2,'PRGOEL','PAL_CONTROL_T','IN');
INSERT INTO PAL_SVM_PDATA_TBL VALUES (3,'PRGOEL','PAL_SVM_MODEL_T','OUT');

CALL SYS.AFLLANG_WRAPPER_PROCEDURE_DROP('PRGOEL','PAL_SVM_TRAIN');

CALL SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL','SVMTRAIN','PRGOEL','PAL_SVM_TRAIN',PAL_SVM_PDATA_TBL);


DROP TABLE PAL_SVM_TRAINING_TBL;
CREATE COLUMN TABLE PAL_SVM_TRAINING_TBL LIKE PAL_SVM_TRAINING_T;

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL LIKE PAL_CONTROL_T;

DROP TABLE PAL_SVM_MODEL_TBL_EX1;
CREATE COLUMN TABLE PAL_SVM_MODEL_TBL_EX1 LIKE PAL_SVM_MODEL_T;

INSERT INTO PAL_SVM_TRAINING_TBL VALUES(0,1,10,100,'A',1);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(1,1.1,10.1,100,'A',1);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(2,1.2,10.2,100,'A',1);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(3,1.3,10.4,100,'A',1);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(4,1.2,10.3,100,'AB',1);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(5,4,40,400,'AB',2);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(6,4.1,40.1,400,'AB',2);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(7,4.2,40.2,400,'AB',2);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(8,4.3,40.4,400,'AB',2);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(9,4.2,40.3,400,'AB',2);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(10,9,90,900,'B',3);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(11,9.1,90.1,900,'A',3);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(12,9.2,90.2,900,'B',3);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(13,9.3,90.4,900,'A',3);
INSERT INTO PAL_SVM_TRAINING_TBL VALUES(14,9.2,90.3,900,'A',3);

INSERT INTO #PAL_CONTROL_TBL VALUES('THREAD_NUMBER',8,null,null);
INSERT INTO #PAL_CONTROL_TBL VALUES('KERNEL_TYPE',2,null,null);
INSERT INTO #PAL_CONTROL_TBL VALUES('TYPE',1,null,null);

CALL PRGOEL.PAL_SVM_TRAIN(PAL_SVM_TRAINING_TBL,#PAL_CONTROL_TBL,PAL_SVM_MODEL_TBL_EX1) WITH OVERVIEW;


SELECT * FROM PAL_SVM_MODEL_TBL_EX1;


#TBL_INPUT_DATA